ALTER TABLE extractions
  ADD COLUMN IF NOT EXISTS ai_status TEXT NOT NULL DEFAULT 'pending',
  ADD COLUMN IF NOT EXISTS ai_raw_output JSONB,
  ADD COLUMN IF NOT EXISTS ai_model TEXT,
  ADD COLUMN IF NOT EXISTS ai_provider TEXT,
  ADD COLUMN IF NOT EXISTS ai_generated_at TIMESTAMPTZ;
